web: python manage.py migrate --skip-checks && python manage.py collectstatic --noinput --skip-checks && gunicorn cycling_dashboard.wsgi:application --bind 0.0.0.0:$PORT --workers 4
worker: celery -A cycling_dashboard worker --loglevel=info --concurrency=2
beat: celery -A cycling_dashboard beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
