web: bash start.sh
worker: celery -A cycling_dashboard worker --loglevel=info --concurrency=2
beat: celery -A cycling_dashboard beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
